import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from '../components/Providers';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'pet project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
} : {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
};
